# Generated by Django 3.2.9 on 2021-11-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movierank_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.TextField(default=''),
        ),
    ]
