# Generated by Django 3.2.9 on 2021-11-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_chat_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chat_users',
        ),
    ]
