# Generated by Django 3.2.9 on 2021-11-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate_user_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='total_rank',
            field=models.IntegerField(default=0),
        ),
    ]
