# Generated by Django 3.2.9 on 2021-11-19 01:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_auto_20211118_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='like_users',
            field=models.ManyToManyField(related_name='like_genres', to=settings.AUTH_USER_MODEL),
        ),
    ]
