# Generated by Django 3.2.9 on 2021-11-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20211119_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierank',
            name='rank',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
