# Generated by Django 3.2.9 on 2021-11-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20211119_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='rate_user_count',
            new_name='rank_count',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='total_rank',
            new_name='rank_sum',
        ),
    ]
